export const data = [
    {
        category:'app',
        image:'design0',
    },
    {
        category:'website',
        image:'design1',
    },
    {
        category:'app',
        image:'design2',
    },
    {
        category:'app',
        image:'design3',
    },
    {
        category:'app',
        image:'design4',
    },
    {
        category:'interaction',
        image:'design5',
    },
    {
        category:'interaction',
        image:'design6',
    },
    {
        category:'website',
        image:'design7',
    },
    {
        category:'app',
        image:'design8',
    },

];